longhorn:
  preUpgradeChecker:
    # Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
    jobEnabled: false
  persistence:
    reclaimPolicy: Retain
  defaultBackupStore:
    backupTarget: s3://plat-fra-prod-storage-backup@eu-frankfurt-1/
    backupTargetCredentialSecret: storage-backup
